import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header/header";
import Footer from "@/components/common/footer/footer";
import { Toaster } from "sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        src="https://kit.fontawesome.com/d32ad62e17.js"
        crossOrigin="anonymous"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          richColors
          toastOptions={{
            style: {
              border: "1px solid",
            },
            classNames: {
              // success: "shadow-green-800 border-green-800",
              // content: "!shadow-[5px_5px]",
              toast: "!shadow-[3px_3px] border-1",
            },
          }}
        />
        <Header />
        <main className="min-h-[800px] p-2 py-10  mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
